services:
  cfsdns:
    build: .
    image: wanxve0000/cfsdns:test
    shm_size: '2g'
    environment:
      ALIYUN_ACCESS_KEY_ID: "ALIYUN_ACCESS_KEY_ID"
      ALIYUN_ACCESS_KEY_SECRET: "ALIYUN_ACCESS_KEY_SECRET"
      ALIYUN_PACKAGE_NUM: "100"
      SLEEPTIME: "480"
      domain_rr: "www"
      domain_root: "domian.com"
    tty: true