TEMP_SUBDOMAIN = "temp"
CUSTOM_DNS_SERVER = "119.29.29.29"

DEFAULT_SLEEP_SECONDS = 1800
MIN_RECOMMENDED_SLEEP_SECONDS = 900
RECOMMENDED_SLEEP_SECONDS = 1800
DEFAULT_HEALTHCHECK_TIMEOUT_SECONDS = 10
DEFAULT_HEALTHCHECK_EXPECT_STATUS = 200

FIRST_PASS_REQUIRED_STATUS = "530"
FIRST_PASS_MAX_TOTAL_TIME_SECONDS = 1.0
SECOND_PASS_DELETE_MIN_TOTAL_TIME_SECONDS = 2.0

MAX_CANDIDATE_IPS_PER_CARRIER = 20
MAX_SELECTED_IPS_PER_CARRIER = 8
MAX_CF090227_IPS_PER_CARRIER = 10
MAX_BAD_RECORDS_BEFORE_TRUNCATION = 10
MAX_BAD_RECORDS_TO_DELETE = 5
PRODUCTION_RECORD_FLOOR = 3
PRODUCTION_RECORD_TARGET = 6
PRODUCTION_RECORD_CEILING = 8
MAX_SURPLUS_PRUNE_PER_LINE_PER_CYCLE = 2
CONSECUTIVE_ANOMALY_DELETE_THRESHOLD = 2
GLOBAL_FREEZE_MIN_LINES = 2
GLOBAL_FREEZE_ANOMALY_RATIO = 0.8
RUNTIME_STATE_FILENAME = ".cfsdns_state.json"
PROCESS_LOCK_FILENAME = ".cfsdns.lock"

EXCLUDED_IP_PREFIXES = ("172.65.",)

CARRIER_DISPLAY_NAMES = {
    "mobile": "移动",
    "unicom": "联通",
    "telecom": "电信",
}

DETECTION_POINT_PREFIX_TO_LINE = {
    "移动": "mobile",
    "联通": "unicom",
    "电信": "telecom",
}

IP_SOURCE_URLS = {
    "uouin": "https://api.uouin.com/cloudflare.html",
    "wetest": "https://www.wetest.vip/page/cloudflare/address_v4.html",
    "cf090227": "https://cf.090227.xyz",
    "ip164746": "https://ip.164746.xyz/ipTop10.html",
}

PUBLIC_DOH_ENDPOINTS = (
    "https://dns.google/resolve",
    "https://cloudflare-dns.com/dns-query",
)
